FROM node:18.9.1-slim

RUN apt update && apt install -y wget netcat

#usuario root
RUN wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

USER node

WORKDIR /home/node/app

CMD [ "/home/node/app/.docker/entrypoint.sh" ]