### register Project
POST http://localhost:3003/project
Content-Type: application/json

{
    "name":"test",
    "description":"test"
}

### getAll Projects
GET http://localhost:3003/project

### get One Project
GET http://localhost:3003/project/5

### delete Project
DELETE http://localhost:3003/project/652bd8a0-2537-4698-96bd-5ea6afd97248

### create Task
POST http://localhost:3003/task
Content-Type: application/json 

{
    "name":"mais uma task",
    "description":"mais uma descrição",
    "deadLine":"2022/12/31",
    "projectId":"ff624bda-d1db-49b6-ac6e-68bf61518feb"
}

### find all Tasks
GET http://localhost:3003/task

### find one Task
GET http://localhost:3003/task/13ba2e2c-d1a4-43ab-986f-5132a1b49070

### find all Tasks by project
GET http://localhost:3003/task/project/f84b7bc4-f01f-465d-88c5-8a8889a7e366

### update Task
PATCH http://localhost:3003/task/28a925bd-ee19-4269-8666-b47ce035b0f5
Content-Type: application/json

{
    "completed":true,
    "description":null,
    "name":null
}

### delete Task
DELETE http://localhost:3003/task/13ba2e2c-d1a4-43ab-986f-5132a1b49070