services:
  db:
    build: .docker/mysql
    container_name: mysql-BTX
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}